services:
  nginx:
    container_name: nginxLB
    image: nginx:1.25.4
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ../nginx/index.html
        target: /usr/share/nginx/html/index.html
    environment:
      - TZ=Asia/Seoul
