name: Our First Workflow
on: push
jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - run: echo 'Hellworld, Github Actions!'
    pwd-ls:
      name: PWD&LS
      runs-on: ubuntu-letest
      steps:
        - name: PWD
          run: pwd
        - name: List files
          run: ls -al

