name: Our First Workflow
on: push
jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - run: echo 'Hellworld, Github Actions!'
    pwd-ls:
      name: PWD&LS
      runs-on: ubuntu-latest
      steps:
        - name: Print_Working_Directory
          run: pwd
        - name: List_Files_-al
          run: ls -al

